### PR TITLE
Buttons animation

### PR DESCRIPTION
**Pull request by JoJoDevAdventure**
I created an animation that shows the need to select one desired league to continue to next

### CODE REVIEW

**Comment by JoJoDevAdventure** [comment]
hello, I fixed some code and added some cool animations, hope you like it

**Review by JoJoDevAdventure — COMMENTED** [review]
everything works correctly

**Comment by JoJoDevAdventure** [comment]
fixed conflict

**Review by Amjadoudeh — COMMENTED** [review]
Hey @JoJoDevAdventure,
Could you please add a screenshot / Record to show the changes that you made? 
thank you!

**Comment by JoJoDevAdventure** [comment]
of course, here's a preview :

https://user-images.githubusercontent.com/89042174/171000198-30e07138-e925-4d47-a112-d13b9fd855f9.mp4

**Review by Amjadoudeh — APPROVED** [review]
Nice work! Thanks ;)

**Pull request merged**
