### PR TITLE
UI + Passing Data

### PR DESCRIPTION
**Pull request by JoJoDevAdventure**
Hello Amjad, I added a UI selection and animation in the 'SkillViewController'
Fixed the data passing and Player Model,
here's a preview and a results :
**Preview :**

https://user-images.githubusercontent.com/89042174/171017066-01c7b482-107b-4f7e-8017-b09df278608a.mp4

**Results :**
Screenshot 2022-05-30 at 15 48 49

### CODE REVIEW

**Review by JoJoDevAdventure — COMMENTED** [review]
no conflict and passing data fixed

**Review by JoJoDevAdventure — COMMENTED** [review]
zoom in animation integrated

**Comment by JoJoDevAdventure** [comment]
https://user-images.githubusercontent.com/89042174/171047944-ef223deb-00bb-4247-abef-277ae075a648.mp4

**Review by Amjadoudeh — APPROVED** [review]
Hey Youssef, the animation is giving it more visibility and value, nice work!

**Pull request merged**
